---
title: 'CRD 298: Spatial Methods in Community Research'
---

<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: italic;
}

</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<h4 style="font-style:normal">Professor Noli Brazil</h4>
<h4 style="font-style:normal">University of California, Davis</h4>
<h4 style="font-style:normal">Department of Human Ecology, Community and Regional Development</h4>

\

Welcome to the CRD 298 website!  This website complements the class [Canvas](https://login.canvas.ucdavis.edu/) site.  

On this website you will find:

* An abridged syllabus
* Assignment guidelines 
* Lab and homework assignment material
* Other useful R related material

On Canvas you will find:

* A detailed syllabus
* Reading material
* Lecture slides
* Data for labs/assignments
* Project and midterm material
* Submit your homework
* Grades

\


## About the class

Many community socioeconomic and demographic processes such as poverty, crime, healthy food access, school quality, migration, and segregation have important spatial components.  Spatial data are becoming more ubiquitous and the tools for managing, processing, examining, and modelling these data are becoming more accessible.  This course introduces students to the important theoretical roles that space and place have in community research.  Here, the community is broadly defined as a geographic unit with recognizable boundaries that possesses a resident sense of place.  The course will also have a large analytical component, exposing students to the acquisition, management, examination, and modelling of spatial data for understanding communities.  The course will focus on applications in the social sciences and public health, including demography, epidemiology, sociology, criminology, human geography, public policy, education, and others.  The course assumes you have taken an introductory class in statistics and have an understanding of univariate statistics such as linear regression.  We will be using the statistical program [R](https://www.r-project.org/) in this class. Experience with any statistical package (like Stata, SAS or R) is useful but not required.


***

Website created and maintained by [Noli Brazil](https://nbrazil.faculty.ucdavis.edu/)
