<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Lab 10: Social Network Analysis</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="site_libs/anchor-sections-1.0/anchor-sections.js"></script>
<script src="site_libs/htmlwidgets-1.5.2/htmlwidgets.js"></script>
<link href="site_libs/vis-4.20.1/vis.css" rel="stylesheet" />
<script src="site_libs/vis-4.20.1/vis.min.js"></script>
<script src="site_libs/visNetwork-binding-2.0.9/visNetwork.js"></script>
<link href="site_libs/font-awesome-4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">CRD 230: Winter 2021</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="syllabus.html">Syllabus</a>
</li>
<li>
  <a href="hw_guidelines.html">Assignment Guidelines</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Labs
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="lab1.html">Lab 1</a>
    </li>
    <li>
      <a href="lab2.html">Lab 2</a>
    </li>
    <li>
      <a href="lab3.html">Lab 3</a>
    </li>
    <li>
      <a href="lab4a.html">Lab 4a</a>
    </li>
    <li>
      <a href="lab4b.html">Lab 4b</a>
    </li>
    <li>
      <a href="lab5a.html">Lab 5a</a>
    </li>
    <li>
      <a href="lab5b.html">Lab 5b</a>
    </li>
    <li>
      <a href="lab6a.html">Lab 6a</a>
    </li>
    <li>
      <a href="lab6b.html">Lab 6b</a>
    </li>
    <li>
      <a href="lab7.html">Lab 7</a>
    </li>
    <li>
      <a href="lab8.html">Lab 8</a>
    </li>
    <li>
      <a href="lab9.html">Lab 9</a>
    </li>
    <li>
      <a href="lab10.html">Lab 10</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Other
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="tips.html">R tips</a>
    </li>
    <li>
      <a href="ndata.html">Data Sources</a>
    </li>
    <li>
      <a href="nhgis.html">NHGIS</a>
    </li>
    <li>
      <a href="policymap.html">PolicyMap</a>
    </li>
    <li>
      <a href="censusgeography.html">Census Geographies</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">

<div class="btn-group pull-right">
<button type="button" class="btn btn-default btn-xs dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Lab 10: Social Network Analysis</h1>
<h3 class="subtitle"><h4 style="font-style:normal">
CRD 230 - Spatial Methods in Community Research
</h4></h3>
<h4 class="author"><h4 style="font-style:normal">
Professor Noli Brazil
</h4></h4>
<h4 class="date"><h4 style="font-style:normal">
March 4, 2021
</h4></h4>

</div>


<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: italic;
}

h1.title {
  font-weight: bold;
  font-family: Arial;  
}

h2.title {
  font-family: Arial;  
}

</style>
<style type="text/css">
#TOC {
  font-size: 13px;
  font-family: Arial;
}
</style>
<p><br />
</p>
<p>For most of this quarter, we’ve conceptualized connectivity and dependence from a purely spatial perspective. In this lab, we will examine how neighborhood linkages can be shaped by networks that transcend geographic connectivity. To do this, we will dive into the world of social network analysis (SNA). The objectives of this guide are as follows</p>
<ol style="list-style-type: decimal">
<li>Learn how to construct a social network object in R</li>
<li>Learn how to visualize a social network</li>
<li>Learn how to calculate node and network-level summary statistics</li>
<li>Learn how to incorporate network connectivity in a spatial regression model</li>
<li>Learn how to create spatial network objects using the <strong>sfnetworks</strong> package</li>
</ol>
<p>To help us accomplish these learning objectives, we will construct a social network linking census tracts in the City of Seattle based on <a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1745-9125.2012.00281.x">gang turfs</a>. The material covered in this lab follows closely the material covered in Handout 8.</p>
<div style="margin-bottom:25px;">

</div>
<div id="installing-and-loading-packages" class="section level2">
<h2><strong>Installing and loading packages</strong></h2>
<p><br />
</p>
<p>We’ll be using the following new packages in this lab. Install them using <code>install.packages()</code>.</p>
<pre class="r"><code>install.packages(&quot;tidygraph&quot;)
install.packages(&quot;ggraph&quot;)
install.packages(&quot;igraph&quot;)
install.packages(&quot;visNetwork&quot;)</code></pre>
<p>Load in all necessary packages for this lab.</p>
<pre class="r"><code>library(tidyverse)
library(sf)
library(tmap)
library(spdep)
library(spatialreg)
library(knitr)
library(tidygraph)
library(ggraph)
library(igraph)
library(visNetwork)</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="bring-in-census-tract-data" class="section level2">
<h2><strong>Bring in census tract data</strong></h2>
<p><br />
</p>
<p>We will be using the shapefile <em>seattle_census_tracts_2010.shp</em>. This file contains violent crime counts and rates between 2014 and 2017 by census tract in Seattle, WA. It also contains demographic and socioeconomic data from the 2012-16 American Community Survey. The record layout for the shapefile’s attribute table is located <a href="https://raw.githubusercontent.com/crd230/data/master/seattle_record_layout.txt">here</a>.</p>
<p>I zipped up the files associated with the shapefile and uploaded the file onto Github. Download the file, unzip it, and bring it into R using the following code.</p>
<pre class="r"><code>download.file(url = &quot;https://raw.githubusercontent.com/crd230/data/master/seattle_census_tracts_2010.zip&quot;, destfile = &quot;seattle_census_tracts_2010.zip&quot;)
unzip(zipfile = &quot;seattle_census_tracts_2010.zip&quot;)

sea.tracts &lt;- st_read(&quot;seattle_census_tracts_2010.shp&quot;, stringsAsFactors = FALSE)</code></pre>
<p>We’re going to examine the association between structural neighborhood characteristics and violent crime rates in the City of Seattle. Specifically, we will examine the association between violent crime and residential mobility, concentrated disadvantage, immigrant concentration, population density, percent of housing units that are owner occupied, and population density. Let’s create the concentrated disadvantage (mean standardized values of percent poverty, percent unemployed, percent non-Hispanic black, percent under 18 years old, and percent on public assistance) and immigrant concentration (mean standardized values of percent Hispanic and percent foreign born) indices using the following code. We covered these functions in <a href="https://crd230.github.io/lab6b.html#Standardize_and_Average">Lab 6b</a>.</p>
<pre class="r"><code>sea.tracts.std &lt;- sea.tracts %&gt;%
                  st_drop_geometry() %&gt;%
                  mutate_at(~(scale(.) %&gt;% as.vector(.)), 
                    .vars = vars(ppov, unemp, pnhblack, pund18, pwelfare)) %&gt;%
                  mutate(concd = (ppov+unemp+pnhblack+pund18+pwelfare)/5, 
                         immc = (pfb+phisp)/2) %&gt;%
                  select(GEOID10, concd, immc)

#merge indices into main analysis file
sea.tracts &lt;- left_join(sea.tracts, sea.tracts.std, by = &quot;GEOID10&quot;)</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="bring-in-network-data" class="section level2">
<h2><strong>Bring in network data</strong></h2>
<p><br />
</p>
<p>There are numerous network analysis packages in R. We’ll be using the packages <strong>igraph</strong>, perhaps the most relied upon social network package in R (that or the suite of <a href="http://www.statnet.org/">statnet packages</a>) and <strong>tidygraph</strong> and <strong>ggraph</strong>, which leverage the power of <strong>igraph</strong> in a manner consistent with the tidyverse workflow we’re now accustomed to. <a href="https://www.data-imaginist.com/2018/tidygraph-1-1-a-tidy-hope/">Here</a> is a vignette of <strong>tidygraph</strong>. <a href="https://igraph.org/redirect.html">Here</a> is the <strong>igraph</strong> website and <a href="https://www.r-project.org/conferences/useR-2008/slides/Csardi.pdf">lecture slides</a> providing a brief background on the package. Finally, find <strong>ggraph</strong> vignettes from its creator <a href="https://cran.r-project.org/web/packages/ggraph/vignettes/Edges.html">here</a>, <a href="https://cran.r-project.org/web/packages/ggraph/vignettes/Layouts.html">here</a>, and <a href="https://cran.r-project.org/web/packages/ggraph/vignettes/Nodes.html">here</a>. In this lab, we will just scratch the surface on network analysis in R, so I would recommend exploring these resources if you want to use SNA in your research.</p>
<p>The two primary components of networks are nodes or actors, and the connections between them, which are known as edges or ties. There are two ways to construct a network graph.</p>
<div style="margin-bottom:25px;">

</div>
<div id="sociomatrix" class="section level3">
<h3><strong>Sociomatrix</strong></h3>
<p><br />
</p>
<p>First, you can use sociomatrices, also known as adjacency matrices. An adjacency matrix is a square matrix in which the column and row names are the nodes of the network. Within the matrix a 1 indicates that there is a connection between the nodes (edge), and a 0 indicates no connection. If the network is weighted, the values of the cells will measure the degree to which the node in the row interacts with the node in the column. Let’s bring in the sociomatrix for neighborhood gang affiliation in Seattle. I created this matrix outside of R and uploaded it onto GitHub.</p>
<pre class="r"><code>gang.matrix &lt;- read_csv(&quot;https://raw.githubusercontent.com/crd230/data/master/seattle_gang_tracts.csv&quot;)</code></pre>
<p>The matrix contains census tracts as rows and columns. The matrix does not distinguish between which specific gangs are in which neighborhoods - a value of 1 indicates that the neighborhoods on the row and column are in the same gang turf. Note that a neighborhood cannot be associated with multiple gangs (i.e. a neighborhood can only belong to one gang turf). The gang turf network is undirected. An adjacency matrix is always symmetric if you are dealing with an undirected network. Note that these data are outdated (2017), and thus should not be used in an analysis of contemporary data. Moreover, the data were compiled via newspapers articles and social media, and therefore may contain errors.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="node-and-edge-lists" class="section level3">
<h3><strong>Node and edge lists</strong></h3>
<p><br />
</p>
<p>The second way to construct a network object is to use a node list and an edgelist. An edgelist is a data frame that contains a minimum of two columns, one column of nodes that are the source of a connection and another column of nodes that are the target of the connection. The nodes in the data are identified by unique IDs. If the distinction between source and target is meaningful, the network is directed. If the distinction is not meaningful, the network is undirected. In our case study, our network is undirected. Let’s bring in the edgelist, which I uploaded onto Github.</p>
<pre class="r"><code>sea.edges &lt;- read_csv(&quot;https://raw.githubusercontent.com/crd230/data/master/edges.csv&quot;)</code></pre>
<p>Take a look</p>
<pre class="r"><code>glimpse(sea.edges)</code></pre>
<pre><code>## Rows: 90
## Columns: 2
## $ from &lt;dbl&gt; 5, 5, 21, 21, 22, 22, 22, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24,…
## $ to   &lt;dbl&gt; 104, 136, 50, 51, 36, 40, 46, 24, 36, 46, 48, 59, 64, 65, 36, 46,…</code></pre>
<p>We also need to establish a node list, which is a data frame with a column that lists the node IDs for all nodes in the network regardless of whether they have a connection to other network nodes. Let’s bring in the node list.</p>
<pre class="r"><code>sea.nodes &lt;- read_csv(&quot;https://raw.githubusercontent.com/crd230/data/master/nodes.csv&quot;)</code></pre>
<p>Take a gander</p>
<pre class="r"><code>glimpse(sea.nodes)</code></pre>
<pre><code>## Rows: 140
## Columns: 2
## $ id    &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 1…
## $ label &lt;dbl&gt; 26700, 26600, 800, 700, 600, 500, 402, 401, 300, 200, 100, 26500…</code></pre>
<p>The node list contains the <em>id</em> that defines the connection in the <em>to</em> and <em>from</em> columns in the edgelist and the tract FIPS code associated with the <em>id</em>.</p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="create-the-network-object" class="section level2">
<h2><strong>Create the network object</strong></h2>
<p><br />
</p>
<div style="margin-bottom:25px;">

</div>
<div id="sociomatrix-1" class="section level3">
<h3><strong>Sociomatrix</strong></h3>
<p><br />
</p>
<p>We can create a network object from the adjacency matrix using the function <code>graph_from_adjacency_matrix()</code>, which is a part of the <strong>igraph</strong> package. We’ll need to clean up this matrix a bit before we can input it into <code>graph_from_adjacency_matrix()</code>. First, we want just 0 and 1 values in the matrix cells, so get rid of the column <em>X1</em>, which provides the tract IDs.</p>
<pre class="r"><code>gang.matrix &lt;- gang.matrix %&gt;%
                select(-X1)</code></pre>
<p>Next, designate row names using the column names of the data frame, which are the tract IDs.</p>
<pre class="r"><code>rownames(gang.matrix) &lt;- colnames(gang.matrix)</code></pre>
<p>Now we can use <code>graph_from_adjacency_matrix()</code> to create an <strong>igraph</strong> network object. The function <code>graph_from_adjacency_matrix()</code> takes in a <em>matrix</em> object, so we’ll need to use <code>as.matrix()</code> to convert <em>gang.matrix</em> to a matrix, which is currently a tibble.</p>
<pre class="r"><code>class(gang.matrix)</code></pre>
<pre><code>## [1] &quot;tbl_df&quot;     &quot;tbl&quot;        &quot;data.frame&quot;</code></pre>
<p>We’ll also need to specify that the network is undirected using the argument <code>mode = "undirected"</code></p>
<pre class="r"><code>gang.network.ig &lt;- graph_from_adjacency_matrix(as.matrix(gang.matrix), 
                                               mode = &quot;undirected&quot;)</code></pre>
<p>We’ll want to convert the <strong>igraph</strong> network object into a tidy network object so it can cohere with all the tidy functions we’ve learned in this class. To do this, use the function <code>as_tbl_graph()</code></p>
<pre class="r"><code>gang.network1&lt;-as_tbl_graph(gang.network.ig)</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="node-and-edge-lists-1" class="section level3">
<h3><strong>Node and edge lists</strong></h3>
<p><br />
</p>
<p>We create a network from an edge list and a node list using the function <code>tbl_graph()</code>, which is a part of the <strong>igraph</strong> package. The node list <em>sea.nodes</em> is a regular tibble with two columns indicating a generic ID from 1 to 140 for each tract and the tract FIPS code. What is the purpose of the ID of 1 to 140? Because the function <code>tbl_graph()</code>, which creates a network object from node and edge lists, assumes that there should be nodes for <em>every integer between</em> <code>min(node$id)</code> and <code>max(node$id)</code>, which is not the case if we use the FIPS tract code.</p>
<p>In <code>tbl_graph()</code>, we specify the nodes and edges using the <code>nodes =</code> and <code>edges =</code> arguments, respectively. We use the argument <code>directed = FALSE</code> to tell R that we want to create an undirected network.</p>
<pre class="r"><code>gang.network2 &lt;- tbl_graph(nodes = sea.nodes, edges = sea.edges, directed = FALSE)</code></pre>
<p>The output for <em>gang.network2</em> is similar to that of a normal tibble.</p>
<pre class="r"><code>gang.network2</code></pre>
<pre><code>## # A tbl_graph: 140 nodes and 90 edges
## #
## # An undirected simple graph with 101 components
## #
## # Node Data: 140 x 2 (active)
##      id label
##   &lt;dbl&gt; &lt;dbl&gt;
## 1     1 26700
## 2     2 26600
## 3     3   800
## 4     4   700
## 5     5   600
## 6     6   500
## # … with 134 more rows
## #
## # Edge Data: 90 x 2
##    from    to
##   &lt;int&gt; &lt;int&gt;
## 1     5   104
## 2     5   136
## 3    21    50
## # … with 87 more rows</code></pre>
<p>The object <em>gang.network2</em> is separated into node and edge tables. Edge Data is a table of all relationships between <em>from</em> and <em>to</em>. Node Data is a table containing all of the IDs and FIPS codes of the tracts even if they do not appear in the Edge Data table (not all 140 tracts are part of a gang turf).</p>
<p>We find that there are 140 nodes (census tracts) and 90 edges. The first six rows of “Node Data” and the first three of “Edge Data” are also shown.</p>
<p>Run the command <code>class()</code> on <em>gang.network2</em> and you’ll find that <strong>tidygraph</strong> sub classes <strong>igraph</strong> with the <em>tbl_graph</em> class and thus presents the network in a tidy manner.</p>
<pre class="r"><code>class(gang.network2)</code></pre>
<pre><code>## [1] &quot;tbl_graph&quot; &quot;igraph&quot;</code></pre>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="visualizing-your-network" class="section level2">
<h2><strong>Visualizing your network</strong></h2>
<p><br />
</p>
<p>There are a number of ways to visualize your network. The most common approach is to graph the network’s nodes and edges onto a two-dimensional space. The tidy package for graphing networks is <code>ggraph</code>, which is an extension of <strong>ggplot2</strong>, making it easier to carry over the basic <code>ggplot()</code> skills we learned in <a href="https://crd230.github.io/lab2.html#Summarizing_variables_using_graphs">Lab 2</a> to the creation of network plots in this lab.</p>
<p>Let’s plot the Seattle neighborhood gang turf network using <code>ggraph()</code></p>
<pre class="r"><code>gang.network2 %&gt;%
  ggraph(layout = &quot;fr&quot;) + 
  geom_edge_link() + 
  geom_node_point() + 
  ggtitle(&quot;Gang Turf Network in Seattle, WA&quot;)</code></pre>
<p><img src="lab10_files/figure-html/unnamed-chunk-18-1.png" /><!-- --></p>
<p>As you can see, the structure of the command <code>ggraph()</code> is similar to that of <code>ggplot()</code> with the separate layers added with the <code>+</code> sign. The first step is to establish a layout using the argument <code>layout =</code> in <code>ggraph()</code>. The layout parameter specifies the algorithm to use to display the graph. In other words, a layout is the vertical and horizontal placement of nodes when plotting the graph structure. The “fr” layout is part of the graph layouts package and is always a safe choice since it is deterministic and produces nice layouts for almost any graph. Other layout algorithms are described <a href="https://www.rdocumentation.org/packages/ggraph/versions/2.0.4/topics/layout_tbl_graph_igraph">here</a>. You can get a deeper look into the other ways you can display the network in this <a href="https://www.data-imaginist.com/2017/ggraph-introduction-layouts/">guide</a>. Note that there isn’t anything geographic about the above plot - the location of the points in the plot are not linked or associated with anything referenced on the earth’s surface.</p>
<p>The functions <code>geom_edge_link()</code> and <code>geom_node_point()</code> plots the edges and nodes, respectively. And there are arguments within these commands to stylize and alter their graphical features. Network visualizations are cool if you’ve got a small enough data set. Check out the <strong>ggraph</strong> <a href="https://cran.r-project.org/web/packages/ggraph/index.html">vignettes</a> to find out how you can improve your graphics.</p>
<p>Just like with interactive maps, you can also make interactive network graphs. You can do this by using the package <strong>visNetwork</strong>. Use the function <code>toVisNetworkData()</code> to initialize the interactive graph. The argument <code>idToLabel = FALSE</code> tells R not to use the column <em>id</em> to identify the nodes. It will instead grab the column <em>label</em></p>
<pre class="r"><code>dataVis &lt;-  toVisNetworkData(gang.network2,idToLabel = FALSE)</code></pre>
<p>You then create the interactive network using the function <code>visNetwork()</code>. Similar to <code>ggraph()</code> you can make this interactive visual <a href="https://cran.r-project.org/web/packages/visNetwork/vignettes/Introduction-to-visNetwork.html">prettier</a>.</p>
<pre class="r"><code>visNetwork(nodes = dataVis$nodes, edges = dataVis$edges, width = &quot;100%&quot;,
           main = &quot;Gang Turf Network in Seattle Neighborhoods&quot;) %&gt;%
  addFontAwesome() %&gt;%
  visOptions(highlightNearest = list(enabled = T, hover = T), nodesIdSelection = T) %&gt;%
  visInteraction(navigationButtons = TRUE)</code></pre>
<div id="htmlwidget-07ed9ceb15a498248173" style="width:100%;height:480px;" class="visNetwork html-widget"></div>
<script type="application/json" data-for="htmlwidget-07ed9ceb15a498248173">{"x":{"nodes":{"id":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140],"label":[26700,26600,800,700,600,500,402,401,300,200,100,26500,26400,26300,26100,26001,1702,4302,4301,7402,10002,10001,11002,10402,10702,11402,11401,25302,12100,12000,11900,10900,10800,10600,10500,10300,1701,7401,10200,10100,9900,9800,9702,9701,9600,10401,10701,11001,9500,9400,9300,9200,9100,9000,8900,8800,8700,11800,11700,11600,11500,11300,11200,11102,11101,8600,8500,8400,8300,8200,8100,8002,8001,7900,7800,7700,7600,7500,7300,7200,7100,7000,6900,6800,6700,6600,6500,6400,6300,6200,6100,6000,5801,5700,5600,5400,5302,5301,5200,5100,5000,4900,4800,4700,4600,4500,4400,4200,4100,4000,3900,3800,5900,5802,3600,3500,3400,3300,3200,3100,3000,2900,2800,2700,2600,2500,2400,2200,2100,2000,1900,1800,1600,1500,1400,1300,1200,1100,1000,900]},"edges":{"from":[5,5,21,21,22,22,22,23,23,23,23,23,23,23,24,24,24,24,24,24,25,25,25,25,25,25,25,31,31,33,33,33,33,33,33,34,34,35,35,35,35,36,36,36,36,36,36,36,40,41,46,46,46,46,46,47,48,48,48,48,50,50,50,53,53,53,54,54,54,54,56,56,56,56,57,57,58,58,58,59,59,64,66,71,71,72,74,98,98,104],"to":[104,136,50,51,36,40,46,24,36,46,48,59,64,65,36,46,48,59,64,65,33,34,35,41,42,47,61,58,59,34,35,41,42,47,61,47,61,41,42,53,54,39,40,46,48,60,64,65,46,42,48,58,59,64,65,61,58,59,64,65,51,54,55,54,66,67,55,57,66,67,57,74,75,76,74,76,59,64,65,64,65,65,67,72,80,80,76,104,107,136]},"nodesToDataframe":true,"edgesToDataframe":true,"options":{"width":"100%","height":"100%","nodes":{"shape":"dot"},"manipulation":{"enabled":false},"interaction":{"hover":true,"navigationButtons":true}},"groups":null,"width":"100%","height":null,"idselection":{"enabled":true,"style":"width: 150px; height: 26px","useLabels":true,"main":"Select by id"},"byselection":{"enabled":false,"style":"width: 150px; height: 26px","multiple":false,"hideColor":"rgba(200,200,200,0.5)","highlight":false},"main":{"text":"Gang Turf Network in Seattle Neighborhoods","style":"font-family:Georgia, Times New Roman, Times, serif;font-weight:bold;font-size:20px;text-align:center;"},"submain":null,"footer":null,"background":"rgba(0, 0, 0, 0)","iconsRedraw":true,"highlight":{"enabled":true,"hoverNearest":true,"degree":1,"algorithm":"all","hideColor":"rgba(200,200,200,0.5)","labelOnly":true},"collapse":{"enabled":false,"fit":false,"resetHighlight":true,"clusterOptions":null,"keepCoord":true,"labelSuffix":"(cluster)"},"tooltipStay":300,"tooltipStyle":"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);"},"evals":[],"jsHooks":[]}</script>
<p><br></p>
<p>The widget will allow you to pick a neighborhood and highlight its ego network.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="node-characteristics" class="section level2">
<h2><strong>Node characteristics</strong></h2>
<p><br />
</p>
<p>Let’s now calculate the local network measures covered in Handout 8. In order to do this, we create node-level variables within the graph object <em>gang.network2</em>. Let’s look at the output for <em>gang.network2</em> again.</p>
<pre class="r"><code>gang.network2</code></pre>
<pre><code>## # A tbl_graph: 140 nodes and 90 edges
## #
## # An undirected simple graph with 101 components
## #
## # Node Data: 140 x 2 (active)
##      id label
##   &lt;dbl&gt; &lt;dbl&gt;
## 1     1 26700
## 2     2 26600
## 3     3   800
## 4     4   700
## 5     5   600
## 6     6   500
## # … with 134 more rows
## #
## # Edge Data: 90 x 2
##    from    to
##   &lt;int&gt; &lt;int&gt;
## 1     5   104
## 2     5   136
## 3    21    50
## # … with 87 more rows</code></pre>
<p>Notice the text <em>Node Data: 140 x 2 (active)</em>. This indicates that the Node table is active and any manipulations of the graph object will be done on this table. What if you wanted to manipulate the Edges table? You will need to use the <code>activate()</code> function, which is a part of the <strong>tidygraph</strong> package.</p>
<pre class="r"><code>gang.network2 %&gt;%
  activate(edges)</code></pre>
<pre><code>## # A tbl_graph: 140 nodes and 90 edges
## #
## # An undirected simple graph with 101 components
## #
## # Edge Data: 90 x 2 (active)
##    from    to
##   &lt;int&gt; &lt;int&gt;
## 1     5   104
## 2     5   136
## 3    21    50
## 4    21    51
## 5    22    36
## 6    22    40
## # … with 84 more rows
## #
## # Node Data: 140 x 2
##      id label
##   &lt;dbl&gt; &lt;dbl&gt;
## 1     1 26700
## 2     2 26600
## 3     3   800
## # … with 137 more rows</code></pre>
<p>You’ll see now that the Edge Data is active. The function <code>activate()</code> allows R to know which of the two tables (nodes or edges) to perform further transformations on (the node table is always the default). And because we are in the <strong>tidyverse</strong>, manipulations of the tables take on all the tidy functions we’ve learned throughout this class. For example, let’s filter out the nodes that don’t have an edge. We use the function <code>filter()</code>, which we’ve used extensively throughout this class.</p>
<pre class="r"><code>gang.network.connected &lt;- gang.network2 %&gt;%
  # Remove isolated nodes
  activate(nodes) %&gt;%
  filter(!node_is_isolated())</code></pre>
<p>The command <code>node_is_isolated()</code> is a <strong>tidygraph</strong> function that identifies the nodes that do not have a link and the <code>!</code> sign indicates not, which means when plugged into <code>filter()</code>, remove the nodes that have a <code>TRUE</code> for <code>node_is_isolated()</code>. We get a network that contains only the 43 tracts that are a part of a gang turf.</p>
<pre class="r"><code>gang.network.connected</code></pre>
<pre><code>## # A tbl_graph: 43 nodes and 90 edges
## #
## # An undirected simple graph with 4 components
## #
## # Node Data: 43 x 2 (active)
##      id label
##   &lt;dbl&gt; &lt;dbl&gt;
## 1     5   600
## 2    21 10002
## 3    22 10001
## 4    23 11002
## 5    24 10402
## 6    25 10702
## # … with 37 more rows
## #
## # Edge Data: 90 x 2
##    from    to
##   &lt;int&gt; &lt;int&gt;
## 1     1    41
## 2     1    43
## 3     2    19
## # … with 87 more rows</code></pre>
<p>Now that we know how to activate nodes for manipulation, let’s run through the measures that characterize their connectedness.</p>
<div style="margin-bottom:25px;">

</div>
<div id="centrality" class="section level3">
<h3><strong>Centrality</strong></h3>
<p><br />
</p>
<p>One of the most popular node characteristics is centrality. The higher the centrality, the more central the node. The definition of centrality is pretty broad. As such, there are several measures of centrality. Let’s calculate the three centrality measures covered in Handout 8. The <strong>tidygraph</strong> functions that calculate centrality take on the form <code>centrality_</code>. First, there is degree centrality, which captures the number of relationships (edges) that a node has. Use the function <code>centrality_degree()</code> within <code>mutate()</code> to create a variable named <em>degree</em> that provides node-level degree centrality. Remember, this is a node measure, so make sure the nodes table is activated within your network object.</p>
<pre class="r"><code>gang.network2 &lt;- gang.network2 %&gt;%
                activate(nodes) %&gt;%
                mutate(degree = centrality_degree())</code></pre>
<p>The column <em>degree</em> is a part of the node table in <em>gang.network2</em>.</p>
<pre class="r"><code>gang.network2</code></pre>
<pre><code>## # A tbl_graph: 140 nodes and 90 edges
## #
## # An undirected simple graph with 101 components
## #
## # Node Data: 140 x 3 (active)
##      id label degree
##   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1     1 26700      0
## 2     2 26600      0
## 3     3   800      0
## 4     4   700      0
## 5     5   600      2
## 6     6   500      0
## # … with 134 more rows
## #
## # Edge Data: 90 x 2
##    from    to
##   &lt;int&gt; &lt;int&gt;
## 1     5   104
## 2     5   136
## 3    21    50
## # … with 87 more rows</code></pre>
<p>We can create a degree centrality plot like the one shown in Figure 10 in Handout 8 using our new friend <code>ggraph()</code>. We specify within <code>geom_node_point()</code> that we want to change the size and color of each node based on its degree.</p>
<pre class="r"><code>ggraph(gang.network2, layout = &#39;kk&#39;) + 
  geom_edge_link() + 
  geom_node_point(aes(size = degree, colour = degree)) + 
  scale_color_continuous(guide = &#39;legend&#39;) + 
  theme_graph()</code></pre>
<p><img src="lab10_files/figure-html/unnamed-chunk-27-1.png" /><!-- --></p>
<p>Making nice graphs of networks that are disconnected like <em>gang.network2</em> can be difficult. If the artist in you is calling out, you can make a nice visual using only nodes that are connected. For example, here is a degree centrality plot for the <em>gang.network.connected</em> network with tract labels and a title.</p>
<pre class="r"><code>#create degree variable
gang.network.connected &lt;- gang.network.connected %&gt;%
  mutate(degree = centrality_degree()) 

ggraph(gang.network.connected, layout = &quot;nicely&quot;) + 
  geom_edge_diagonal(alpha = 0.2) + 
  geom_node_point(aes(size = degree)) + 
  scale_color_brewer(palette = &quot;Set1&quot;, name = &quot;Type&quot;) +
  geom_node_text(aes(label = label), size = 2.5, repel = TRUE) +
  theme_graph() +
  theme(plot.background = element_rect(fill = &quot;#f8f2e4&quot;)) +
  labs(title = &quot;Gang Turf Degree Centrality in Seattle Neighborhoods, 2017&quot;,
       size = &quot;Degree&quot;,
       caption = &quot;CRD 230\n Data source: Seattle Police Department&quot;)</code></pre>
<p><img src="lab10_files/figure-html/unnamed-chunk-28-1.png" /><!-- --></p>
<p>Another measure of centrality is betweenness, which captures the number of shortest paths that go through a node. Use the function <code>centrality_betweenness()</code> to create a node-level betweenness variable in <em>gang.network2</em>’s node table.</p>
<pre class="r"><code>gang.network2 &lt;- gang.network2 %&gt;%
                activate(nodes) %&gt;%
                mutate(betweenness = centrality_betweenness())</code></pre>
<p>We then plot node betweenness using <code>ggraph()</code> again.</p>
<pre class="r"><code>gang.network2 %&gt;% 
  ggraph(layout = &#39;kk&#39;) + 
  geom_edge_link() + 
  geom_node_point(aes(size = betweenness, colour = betweenness)) + 
  scale_color_continuous(guide = &#39;legend&#39;) + 
  theme_graph()</code></pre>
<p><img src="lab10_files/figure-html/unnamed-chunk-30-1.png" /><!-- --></p>
<p>The third centrality measure covered in Handout 8 is closeness. Use <code>centrality_closeness()</code> within <code>mutate()</code> to create the variable <em>closeness</em></p>
<pre class="r"><code>gang.network2 &lt;- gang.network2 %&gt;%
                activate(nodes) %&gt;%
                mutate(closeness = centrality_closeness())</code></pre>
<p>Then plot.</p>
<pre class="r"><code>gang.network2 %&gt;% 
  ggraph(layout = &#39;kk&#39;) + 
  geom_edge_link() + 
  geom_node_point(aes(size = closeness, colour = closeness)) + 
  scale_color_continuous(guide = &#39;legend&#39;) + 
  theme_graph()</code></pre>
<p><img src="lab10_files/figure-html/unnamed-chunk-32-1.png" /><!-- --></p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="network-characteristics" class="section level2">
<h2><strong>Network characteristics</strong></h2>
<p><br />
</p>
<p>You’ve successfully created a network object and visualized it. You then measured its node-level characteristics. Next, let’s summarize the overall network. We’ll go through all the network-level measures covered in Handout 8.</p>
<div style="margin-bottom:25px;">

</div>
<div id="average-degree" class="section level3">
<h3><strong>Average degree</strong></h3>
<p><br />
</p>
<p>The first network measured covered in Handout 8 is the average degree. Average degree is just the mean degree across all nodes, or the average number of edges per node in the network. We already created the variable <em>degree</em>, which measures node-level degree centrality. We just take the mean of that variable. Heck, why not take the max, the median, and other summary statistics. To do this, we activate the nodes table, pipe it into the function <code>as_tibble()</code> to transform the table into a tibble, and use the function <code>summarize()</code> to calculate summary statistics.</p>
<pre class="r"><code>gang.network2 %&gt;%
  activate(nodes) %&gt;%
  as_tibble() %&gt;%
  summarize(mean = mean(degree),
            max = max(degree),
            median = median(degree)) %&gt;%
  kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">mean</th>
<th align="right">max</th>
<th align="right">median</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1.285714</td>
<td align="right">10</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>The current active data can be extracted as a tibble using <code>as_tibble()</code>. Here, we find that average number of tracts within a single gang turf is 1.29. But, these data are likely skewed, with a large number of tracts not belonging to a gang turf. We can visualize this using a bar graph.</p>
<pre class="r"><code>gang.network2 %&gt;%
            activate(nodes) %&gt;%
            as_tibble() %&gt;%
            ggplot() +
            geom_bar(aes(x =degree))</code></pre>
<p><img src="lab10_files/figure-html/unnamed-chunk-34-1.png" /><!-- --></p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="centralization" class="section level3">
<h3><strong>Centralization</strong></h3>
<p><br />
</p>
<p>We covered node-level measures of centrality above. There are also network-level measures of centrality. Network centralization is a measure of the unevenness of the centrality scores of actors in a network. It measures the extent to which the actors in a social network differ from one another in their individual centralities. Centralization ranges from zero, when every actor is just as central for whatever centrality score we are interested in, to 1, when one node is maximally central and all others are minimally central.</p>
<p>To measure network-level centrality, we use the suite of <code>centr_</code> functions in <strong>igraph</strong>. To get network degree centrality, use the function <code>centr_degree()</code>. The actual centrality value is stored in the scalar vector <em>centralization</em>, which we extract using the <code>$</code> symbol.</p>
<pre class="r"><code>centr_degree(gang.network2)$centralization</code></pre>
<pre><code>## [1] 0.0626927</code></pre>
<p>Use <code>centr_betw()</code> to get network betweenness centrality.</p>
<pre class="r"><code>centr_betw(gang.network2)$centralization</code></pre>
<pre><code>## [1] 0.01299105</code></pre>
<p>Finally, <code>centr_clo()</code> to measure closeness centrality.</p>
<pre class="r"><code>centr_clo(gang.network2)$centralization</code></pre>
<pre><code>## [1] 0.001867652</code></pre>
<p>Remember from the handout that there are many flavors of centrality (node and network level). Degree, betweenness and closeness are the most popular flavors.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="clustering" class="section level3">
<h3><strong>Clustering</strong></h3>
<p><br />
</p>
<p>We might be interested in measuring the level of clustering in the network. Broadly, clustering captures the degree to which nodes in a graph tend to cluster together. One of the most common measures of clustering is transitivity, which refers to the extent to which the relations that ties nodes in a network are transitive. Perfect transitivity implies that, if neighborhood 1 is connected (through an edge) to neighborhood 2, and neighborhood 2 is connected to neighborhood 3, then neighborhood 1 is connected to neighborhood 3 as well. We use the function <code>transitivity()</code> to measure transitivity, which is a part of the <strong>igraph</strong> package.</p>
<pre class="r"><code>transitivity(gang.network2)</code></pre>
<pre><code>## [1] 0.6966825</code></pre>
<p>If neighborhood 1 is affiliated with neighborhood 2 and neighborhood 2 is affiliated with neighborhood 3 through a gang turf, then the probability that neighborhood 1 is affiliated with neighborhood 3 through a gang turf is 69.7 percent.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="diameter" class="section level3">
<h3><strong>Diameter</strong></h3>
<p><br />
</p>
<p>Another important network summary statistic is the diameter, which gives the length (in number of edges) of the longest geodesic path between any two nodes that are connected.</p>
<pre class="r"><code>diameter(gang.network2)</code></pre>
<pre><code>## [1] 6</code></pre>
<p>The value 6 means that longest geodesic path to go from one neighborhood to another is 6. We can get this path by using the <code>get_diameter()</code> function</p>
<pre class="r"><code>get_diameter(gang.network2)</code></pre>
<pre><code>## + 7/140 vertices, from eb5e498:
## [1] 34 25 35 54 57 56 75</code></pre>
<p>What do the results tell us?</p>
<p>The mean distance of the shortest paths from one neighborhood to another can be calculated using the function <code>mean_distance()</code></p>
<pre class="r"><code>mean_distance(gang.network2)</code></pre>
<pre><code>## [1] 2.468153</code></pre>
<p>Note that this value only considers the connected neighborhoods.</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="density" class="section level3">
<h3><strong>Density</strong></h3>
<p><br />
</p>
<p>The density of a graph is a measure of how many ties between actors exist compared to how many ties between actors are possible. To get the density of a network, use the function <code>graph.density()</code>, which is a part of the <strong>tidygraph</strong> package.</p>
<pre class="r"><code>graph.density(gang.network2) </code></pre>
<pre><code>## [1] 0.009249743</code></pre>
<p>The value is calculated using Equation 3 on page 13 of Handout 8.</p>
<div style="margin-bottom:25px;">

</div>
</div>
</div>
<div id="social-and-spatial-network-models" class="section level2">
<h2><strong>Social and spatial network models</strong></h2>
<p><br />
</p>
<p>We’ve visualized and summarized at the node and network levels the gang neighborhood network in Seattle. Although our network is inherently spatial (e.g. gang turfs encompass a physical space, our network is a connection between neighborhoods across a city), everything we’ve done so far has been <em>aspatial</em>. Let’s now go through some ways to incorporate “spatiality” into our network analyses (or, conversely, ways to incorporate SNA into our spatial analyses).</p>
<p>One simple thing we can do is map the node characteristics we calculated above to find out what our network looks like geographically and identify <em>where</em> the most influential or connected nodes are physically located. First, let’s take out the node tibble from <em>gang.network2</em> using the function <code>as_tibble()</code>. Remember, make sure the node tibble is active.</p>
<pre class="r"><code>node.centrality &lt;-gang.network2 %&gt;%
                  activate(nodes) %&gt;%
                  as_tibble()
node.centrality</code></pre>
<p>You’ll find that the tibble contains the tract ID, FIPS tract code <em>label</em>, and measures of centrality.</p>
<p>Join the centrality measures from <em>node.centrality</em> to the spatial object <em>sea.tracts</em>. We’ll join using the FIPS tract code <em>TRACTCE10</em>, which we’ll need to turn into a numeric in <em>sea.tracts</em>.</p>
<pre class="r"><code>sea.tracts&lt;- sea.tracts %&gt;%
            mutate(TRACTCE10 = as.numeric(TRACTCE10)) %&gt;%
            left_join(node.centrality, by = c(&quot;TRACTCE10&quot; = &quot;label&quot;))</code></pre>
<p>We can then map degree centrality</p>
<pre class="r"><code>tm_shape(sea.tracts, unit = &quot;mi&quot;) +
  tm_polygons(col = &quot;degree&quot;, style = &quot;jenks&quot;,palette = &quot;Reds&quot;, 
              border.alpha = 0, title = &quot;&quot;) +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = 1, position = c(&quot;left&quot;, &quot;bottom&quot;)) +
  tm_layout(main.title = &quot;Gang network degree centrality&quot;,  main.title.size = 0.95, frame = FALSE, legend.outside = TRUE)</code></pre>
<p><img src="lab10_files/figure-html/unnamed-chunk-45-1.png" /><!-- --></p>
<p>What about betweenness centrality?</p>
<pre class="r"><code>tm_shape(sea.tracts, unit = &quot;mi&quot;) +
  tm_polygons(col = &quot;betweenness&quot;, style = &quot;jenks&quot;,palette = &quot;Reds&quot;, 
              border.alpha = 0, title = &quot;&quot;) +
  tm_scale_bar(breaks = c(0, 1, 2), text.size = 1, position = c(&quot;left&quot;, &quot;bottom&quot;)) +
  tm_layout(main.title = &quot;Gang network betweenness centrality&quot;,  main.title.size = 0.95, frame = FALSE, legend.outside = TRUE)</code></pre>
<p><img src="lab10_files/figure-html/unnamed-chunk-46-1.png" /><!-- --></p>
<p>We can also calculate whether a node measure is spatially clustered using the Moran’s I. Let’s do this for degree centrality. Let’s define a row standardized spatial weights matrix using Queen contiguity using the functions we learned in <a href="https://crd230.github.io/lab7.html">Lab 7</a>.</p>
<pre class="r"><code>seab&lt;-poly2nb(sea.tracts, queen=T)
seaw&lt;-nb2listw(seab, style=&quot;W&quot;, zero.policy = TRUE)</code></pre>
<p>Then calculate Moran’s I</p>
<pre class="r"><code>moran.mc(sea.tracts$degree, seaw, nsim=999)</code></pre>
<pre><code>## 
##  Monte-Carlo simulation of Moran I
## 
## data:  sea.tracts$degree 
## weights: seaw  
## number of simulations + 1: 1000 
## 
## statistic = 0.63442, observed rank = 1000, p-value = 0.001
## alternative hypothesis: greater</code></pre>
<p>What does the Moran’s I value tell you about the spatial clustering of gang network degree centrality in Seattle tracts?</p>
<p>As discussed in Handout 8, many of the methods we learned in Labs 7 and 8 using a spatial weights matrix can be applied using a social network or sociomatrix. In other words, the adjacency matrix can be plugged into a spatial regression framework - rather than a spatial weights matrix, we’re dealing with a social network weights matrix. This means we can apply the methods we’ve used to measure and model spatial dependency to measure and model social dependency.</p>
<p>You’ll need to first convert <em>gang.matrix</em> into a row-standardized weights matrix using the function <code>mat2listw()</code>, which is a part of the <strong>spdep</strong> package. We also need to convert the tibble <em>gang.matrix</em> into a matrix using <code>as.matrix()</code>.</p>
<pre class="r"><code>gang.matrix.w &lt;- mat2listw(as.matrix(gang.matrix), style=&quot;W&quot;)</code></pre>
<p>We can then plot the connections</p>
<pre class="r"><code>centroids &lt;- st_centroid(st_geometry(sea.tracts))
plot(st_geometry(sea.tracts), main = &quot;Gang turf network&quot;)
plot.listw(gang.matrix.w, coords = centroids, add = T, col = &quot;red&quot;)</code></pre>
<p><img src="lab10_files/figure-html/unnamed-chunk-50-1.png" /><!-- --></p>
<p>How does this map compare to, say, a map showing connections based on a queen contiguity spatial weights matrix?</p>
<pre class="r"><code>par(mfrow = c(1, 2))
plot(st_geometry(sea.tracts), main = &quot;Gang turf network&quot;)
plot.listw(gang.matrix.w, coords = centroids, add = T, col = &quot;red&quot;)
plot(st_geometry(sea.tracts), main = &quot;Queen contiguity network&quot;)
plot.listw(seaw, coords = centroids, add = T, col = &quot;red&quot;)</code></pre>
<p><img src="lab10_files/figure-html/unnamed-chunk-51-1.png" /><!-- --></p>
<p>It would be neat to combine <code>visNetwork()</code> with, say, <code>leaflet()</code> so that you can create an interactive network and map. I’m not smart enough to construct this, so I will leave this up to the super coders to handle.</p>
<p>You’ve created a weights matrix based on gang turf affiliation. You can then plug this matrix into the spatial regression functions we covered in <a href="https://crd230.github.io/lab8.html#Spatial_lag_model">Lab 8</a> to find out whether gang network dependency has an effect on violent crime rates above and beyond neighborhood structural characteristics. For example, use <code>lagsarlm()</code> to run a social network lag model. You’ll need to add the argument <code>zero.policy=TRUE</code> because of the isolates in the city. We regress the log violent crime rate <em>lvcmrt1417</em> on concentrated disadvantage <em>concd</em>, residential mobility <em>mob</em>, percent home ownership <em>pocc</em>, immigrant concentration <em>immc</em>, and population density <em>pod</em>.</p>
<pre class="r"><code>fit.lag.net&lt;-lagsarlm(lvcmrt1417 ~ concd + mob + pocc + immc  + popd, 
     data = sea.tracts, listw = gang.matrix.w, zero.policy=TRUE) 
summary(fit.lag.net)</code></pre>
<pre><code>## 
## Call:lagsarlm(formula = lvcmrt1417 ~ concd + mob + pocc + immc + popd, 
##     data = sea.tracts, listw = gang.matrix.w, zero.policy = TRUE)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -4.91388 -0.55986  0.20336  1.17533  3.76124 
## 
## Type: lag 
## Regions with no neighbours included:
##  26700 26600 800 700 500 402 401 300 200 100 26500 26400 26300 26100 26001 1702 4302 4301 7402 11402 11401 25302 12100 12000 10900 1701 7401 9702 9701 9600 9500 9200 11600 11300 11200 8400 8300 8200 8001 7600 7500 7300 7100 7000 6900 6800 6700 6600 6500 6400 6300 6200 6100 6000 5801 5700 5600 5400 5302 5200 5100 5000 4900 4800 4600 4500 4200 4100 4000 3900 3800 5900 5802 3600 3500 3400 3300 3200 3100 3000 2900 2800 2700 2600 2500 2400 2200 2100 2000 1900 1800 1600 1500 1400 1200 1100 1000 900 
## Coefficients: (asymptotic standard errors) 
##                Estimate  Std. Error z value Pr(&gt;|z|)
## (Intercept)  3.41870115  4.87099489  0.7018 0.482774
## concd       -0.43214007  0.33702903 -1.2822 0.199771
## mob          4.19446252  1.39910190  2.9980 0.002718
## pocc         0.08753576  5.01052176  0.0175 0.986061
## immc         2.88351427  3.15872225  0.9129 0.361309
## popd        -0.00134536  0.00050164 -2.6819 0.007320
## 
## Rho: 0.24589, LR test value: 19.108, p-value: 1.2352e-05
## Asymptotic standard error: 0.054203
##     z-value: 4.5365, p-value: 5.7187e-06
## Wald statistic: 20.58, p-value: 5.7187e-06
## 
## Log likelihood: -277.0942 for lag model
## ML residual variance (sigma squared): 3.05, (sigma: 1.7464)
## Number of observations: 140 
## Number of parameters estimated: 8 
## AIC: 570.19, (AIC for lm: 587.3)
## LM test for residual autocorrelation
## test value: 0.059683, p-value: 0.807</code></pre>
<p>You use the same interpretations here as you did for the models we ran in Lab 8, except instead of a spatial diffusion effect, you’re modelling a social network diffusion effect. You can compare the findings from these models to a spatial dependency model using Queen contiguity. This is the approach that Papachristos and Bastomski (2018) used in their American Journal of Sociology paper examining co-offending networks in Chicago.</p>
<pre class="r"><code>fit.lag.geo&lt;-lagsarlm(lvcmrt1417 ~ concd + mob + pocc + immc  + popd, 
     data = sea.tracts, listw = seaw, zero.policy=TRUE) 
summary(fit.lag.geo)</code></pre>
<pre><code>## 
## Call:lagsarlm(formula = lvcmrt1417 ~ concd + mob + pocc + immc + popd, 
##     data = sea.tracts, listw = seaw, zero.policy = TRUE)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -4.86357 -0.55506  0.30286  1.00657  3.71562 
## 
## Type: lag 
## Coefficients: (asymptotic standard errors) 
##                Estimate  Std. Error z value Pr(&gt;|z|)
## (Intercept)  0.79431611  4.60814604  0.1724  0.86314
## concd       -0.03276924  0.30709184 -0.1067  0.91502
## mob          3.07667641  1.33426370  2.3059  0.02112
## pocc         0.44777225  4.71394049  0.0950  0.92432
## immc         3.03096625  2.96848686  1.0210  0.30723
## popd        -0.00065881  0.00047139 -1.3976  0.16224
## 
## Rho: 0.54894, LR test value: 27.102, p-value: 1.9305e-07
## Asymptotic standard error: 0.086788
##     z-value: 6.3251, p-value: 2.5307e-10
## Wald statistic: 40.007, p-value: 2.5307e-10
## 
## Log likelihood: -273.0975 for lag model
## ML residual variance (sigma squared): 2.6965, (sigma: 1.6421)
## Number of observations: 140 
## Number of parameters estimated: 8 
## AIC: 562.19, (AIC for lm: 587.3)
## LM test for residual autocorrelation
## test value: 2.2292, p-value: 0.13542</code></pre>
<p>How do the lag parameters and coefficient estimates from the social network lag model <em>fit.lag.net</em> compare to the spatial lag model <em>fit.lag.geo</em>?</p>
<div style="margin-bottom:25px;">

</div>
</div>
<div id="sfnetworks" class="section level2">
<h2><strong>sfnetworks</strong></h2>
<p><br />
</p>
<p>The methods in the above section do not get us to a complete convergence of the spatial and social network ecosystems in R. A new package, <strong>sfnetworks</strong>, moves us towards that objective. The package provides functions that allow users to create a spatial network based on geolocated points as nodes and lines (e.g. streets, transport networks, river basins, power grids, ecological networks) as edges. We won’t go through this package in detail because it is still in development and its power really resides in having both spatially explicit nodes and edges. Here is a snippet from the package’s <a href="https://luukvdmeer.github.io/sfnetworks/articles/intro.html">vignette</a> that conveys this.</p>
<p><em>In a geospatial network, the nodes always have coordinates in geographic space, and thus, are always described by an sf object. The edges, however, can also be described by just the indices of its end-nodes. This still makes them geospatial, because they start and end at specific points in space, but the spatial information is not explicitly attached to them. Both representations can be useful. In road networks, for example, it makes sense to explicitly draw a line geometry between two nodes, while in geolocated social networks, it probably does not. An sfnetwork supports both types. It can either have edges with a geometry stored in a geometry list column, described by an sf object, or edges that only refer to node indices, described by a regular data frame. We refer to these types of edges as spatially explicit edges and spatially implicit edges respectively.</em></p>
<p>In our case study of gang turfs in Seattle, we have spatially explicit nodes (tracts), but not edges. Nevertheless, we can still create an <strong>sf</strong> network and create some nice spatial network plots and maps.</p>
<p>First, we’ll need to install the package. Because it is still in development, the package is not on CRAN. So we need to install it from the creator’s GitHub website</p>
<pre class="r"><code>remotes::install_github(&quot;luukvdmeer/sfnetworks&quot;)</code></pre>
<p>You might have to update a bunch of new packages. When I did so, I ran into some problems with the <strong>sf</strong> package. I had to remove it and then reinstall it. When you are done installing, load the package in.</p>
<pre class="r"><code>library(sfnetworks)</code></pre>
<p>Next, let’s create an <strong>sfnetwork</strong> object using the function <code>sfnetwork()</code>. The first input is the nodes, which have to be an <strong>sf</strong> POINT object. Our nodes are tracts, which are polygons, but we can use tract centroids, which we already created above with the object <em>centroids</em>. Let’s reproject the centroids into UTM.</p>
<pre class="r"><code>#reproject to UTM NAD 83
centroids &lt;-st_transform(centroids, 
                                 crs = &quot;+proj=utm +zone=10 +datum=NAD83 +ellps=GRS80&quot;)</code></pre>
<p>You then specify the edges in <code>sfnetwork()</code>, which may or may not be spatial (i.e. an <strong>sf</strong> object). In our case, our edges are not explicitly spatial.</p>
<pre class="r"><code>sea_gang_sfnetwork &lt;- sfnetwork(centroids, sea.edges, directed = FALSE)</code></pre>
<p>If we take a look at the object, it looks very similar to a <strong>tidygraph</strong> object, but with geometry attached!</p>
<pre class="r"><code>sea_gang_sfnetwork</code></pre>
<pre><code>## # A sfnetwork with 140 nodes and 90 edges
## #
## # CRS:  NAD83 / UTM zone 10N 
## #
## # An undirected simple graph with 101 components with spatially implicit edges
## #
## # Node Data:     140 x 1 (active)
## # Geometry type: POINT
## # Dimension:     XY
## # Bounding box:  xmin: 544372.9 ymin: 5260910 xmax: 557480.4 ymax: 5286565
##                    x
##          &lt;POINT [m]&gt;
## 1 (547236.4 5261101)
## 2 (547960.5 5262823)
## 3 (553551.4 5284454)
## 4 (552363.2 5284937)
## 5 (550060.9 5285164)
## 6 (547377.9 5285564)
## # … with 134 more rows
## #
## # Edge Data: 90 x 2
##    from    to
##   &lt;int&gt; &lt;int&gt;
## 1     5   104
## 2     5   136
## 3    21    50
## # … with 87 more rows</code></pre>
<p>The <strong>sfnetworks</strong> package does not yet include advanced visualization options. However, a simple plot method is provided, which gives a quick view of how the network looks like.</p>
<pre class="r"><code>#get back to 1x1 plot frame
par(mfrow = c(1, 1))
plot(sea_gang_sfnetwork)</code></pre>
<p><img src="lab10_files/figure-html/unnamed-chunk-59-1.png" /><!-- --></p>
<p>We already produced a similar map above, but it required three lines of somewhat ambiguous code.</p>
<p>We can actually make a much more visually compelling map. We’ll need to spatialize the lines connecting the tracts. To do this, use the <code>to_spatial_explicit</code> function within the <code>convert()</code> function, which draws straight linestring geometries between the <em>to</em> and <em>from</em> nodes of spatially implicit edges.</p>
<pre class="r"><code>sea_gang_sfnetwork &lt;- sea_gang_sfnetwork %&gt;% 
  convert(to_spatial_explicit) </code></pre>
<p>Take a look at <em>sea_gang_sfnetwork</em></p>
<pre class="r"><code>sea_gang_sfnetwork</code></pre>
<pre><code>## # A sfnetwork with 140 nodes and 90 edges
## #
## # CRS:  NAD83 / UTM zone 10N 
## #
## # An undirected simple graph with 101 components with spatially explicit edges
## #
## # Node Data:     140 x 2 (active)
## # Geometry type: POINT
## # Dimension:     XY
## # Bounding box:  xmin: 544372.9 ymin: 5260910 xmax: 557480.4 ymax: 5286565
##                    x .tidygraph_node_index
##          &lt;POINT [m]&gt;                 &lt;int&gt;
## 1 (547236.4 5261101)                     1
## 2 (547960.5 5262823)                     2
## 3 (553551.4 5284454)                     3
## 4 (552363.2 5284937)                     4
## 5 (550060.9 5285164)                     5
## 6 (547377.9 5285564)                     6
## # … with 134 more rows
## #
## # Edge Data:     90 x 4
## # Geometry type: LINESTRING
## # Dimension:     XY
## # Bounding box:  xmin: 545975.2 ymin: 5261665 xmax: 555847.6 ymax: 5285164
##    from    to .tidygraph_edge_index                             geometry
##   &lt;int&gt; &lt;int&gt;                 &lt;int&gt;                     &lt;LINESTRING [m]&gt;
## 1     5   104                     1   (550060.9 5285164, 546878 5279439)
## 2     5   136                     2   (550060.9 5285164, 549352 5283420)
## 3    21    50                     3 (551922.7 5269471, 551889.1 5270762)
## # … with 87 more rows</code></pre>
<p>The lines have coordinates!</p>
<p>Why map just the nodes and edges? We can also map one of the node-level characteristics we measured above. For example, degree centrality. To do this, we need to create a variable <em>degree</em> that calculates degree centrality within the <em>sea_gang_sfnetwork</em> object.</p>
<pre class="r"><code>sea_gang_sfnetwork &lt;- sea_gang_sfnetwork %&gt;%
          mutate(degree = centrality_degree())</code></pre>
<p>Now we can make a choropleth map of degree centrality with lines connecting tracts belonging to the same gang turfs. I could not figure out how to do this using <code>tm_shape()</code> (maybe you can, super coder person). Instead, I use <code>ggplot()</code>. We didn’t really cover the use of <code>ggplot()</code> for mapping, only alluding to it in <a href="https://crd230.github.io/lab4a.html#Kernel_density_map">Lab 4a</a>. Our GWR reference textbook discusses the use of <code>ggplot()</code> for mapping in <a href="https://geocompr.robinlovelace.net/adv-map.html">Chapter 8</a>. We can use <code>ggplot()</code> to create our degree choropleth map using the following code.</p>
<pre class="r"><code>ggplot(sea.tracts) +
  geom_sf(aes(fill = degree)) +
  scale_fill_gradient(low= &quot;white&quot;, high = &quot;red&quot;,  name =&quot;&quot;) +
  geom_sf(data = activate(sea_gang_sfnetwork, &quot;edges&quot;) %&gt;% st_as_sf(), col = &#39;black&#39;) + 
    labs(title = &quot;Degree centrality of Seattle Gang Network&quot;) +
    theme( axis.text =  element_blank(),
    axis.ticks =  element_blank(),
    panel.background = element_blank())</code></pre>
<p><img src="lab10_files/figure-html/unnamed-chunk-63-1.png" /><!-- --></p>
<p>Cool, right? With the tools we learned above, you can overlay the social network over all sorts of variable layers that might influence or be impacted by crime, crime diffusion and/or the creation of gang turfs.</p>
<p>As I mentioned above, <strong>sfnetworks</strong> is a work in progress, but carries a lot of promise. Check out the package updates <a href="https://rdrr.io/github/luukvdmeer/sfnetworks/f/NEWS.md">here</a> to see its development. Once it gets on CRAN, it should be a go to package for combining spatial analysis with social network modelling.</p>
<p>And guess what? Your last badge of the quarter!</p>
<center>
<p><img src="sfnetworklogo.png" style="width:25.0%" /></p>
</center>
<p>And with that, you’re done! <a href="https://www.youtube.com/watch?v=bmZQpbNK7t4">Where’d all the time go?</a></p>
<hr />
<p><a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.</p>
<p>Website created and maintained by <a href="https://nbrazil.faculty.ucdavis.edu/">Noli Brazil</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>


</body>
</html>
