---
title: "Syllabus"
subtitle: <h4 style="font-style:normal">CRD 298 - Spatial Methods in Community Research</h4>
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    theme: cosmo
---

<h4 style="font-style:normal">Winter 2019</h4>

<style>
h1.title {
  font-weight: bold;
}
</style>

\

The following is an abridged version of the course syllabus.  A full course syllabus can be found on the Canvas class website.


<div style="margin-bottom:25px;">
</div>
## **Lecture and Lab Times**

* Lecture: 
    + Monday, 10:00-11:50 am, 109 Olson
* Lab: 
    + Wednesday, 10:00-11:50, 1137 PES

<div style="margin-bottom:25px;">
</div>
## **Instructor**

Dr. Noli Brazil  
*Contact*: nbrazil.at.ucdavis.edu  
*Office hours*: Tuesdays from 1:00-3:00 pm or by appointment, in 2325 Hart Hall.  Please sign up for a slot [here](https://www.wejoinin.com/sheets/eqmhu). Out of courtesy to other students, please do not sign up for more than two 15-minute blocks.  If you do, I will keep only the first two blocks.

<div style="margin-bottom:25px;">
</div>
## **Course Objectives**

In this course, students will gain

* A theoretical understanding of the role of space and place in community-level phenomenon
* An understanding of what kinds of spatial data are available and where to find them
* Proficiency in spatial analytic tools (R) to
    + Manage and process spatial data
    + Descriptively examine spatial data
    + Run spatial models for statistical inference
* An understanding of how these methods are employed in community research

<div style="margin-bottom:25px;">
</div>
## **Course Format**

The course is organized into three phases. A detailed outline of the course is provided in the Course Agenda. 

1. Introduction to spatial data: We will go through the theoretical and methodological framework for spatial data analysis. We will discuss spatial data sources and spatial data wrangling. These first few weeks are also meant to get students comfortable with spatial data in the R environment.
2. Exploratory spatial methods: We will go through exploratory methods in spatial analysis.  These methods are descriptive and suggestive.
3. Inferential spatial methods: We will go through spatial regression methods.  These methods are inferential and attempts to answer questions more from a causal perspective.

Most weeks will adhere to the following flow: The first meeting of the week will contain (1) me lecturing about methods and (2) us discussing how the week’s readings employ the methods.  The second meeting of the week will take place in lab whereby we will apply the methods learned in lecture/discussion using real data in R. All students are expected to actively participate, which means not only being present, but reading all material and engaging in class discussions. 

<div style="margin-bottom:25px;">
</div>
## **Required Readings**

Required reading material is composed of a combination of the following 

1. Journal articles, research reports, and book chapters.

These are available on Canvas.

2.	My handouts

For some topics, in lieu of an article or book chapter, I will provide lecture handouts on Canvas in advance of the assigned class.  


## **Additional Readings**

The other major course material are lab guides, which will be released at the beginning of each lab on the lab website.  Many of the R lab guides will closely follow two textbooks.  These textbooks are not required, but are great resources. 

The first textbook provides the foundation for using R

* (RDS) Wickham, Hadley & Garret Grolemund. (2017). R for Data Science. Sebastopol, CA: O’Reilly Media.

The textbook is free online at: http://r4ds.had.co.nz/introduction.html  

The second textbook covers spatial data in R

* (GWR) Lovelace, Robin, Jakub Nowosad & Jannes Muenchow. Geocomputation with R. CRC Press.

The textbook is free online at: https://geocompr.robinlovelace.net/

<div style="margin-bottom:25px;">
</div>
## **Course Software**

[R](https://www.r-project.org/) is the only statistical language used in this course, as it has become an increasingly popular program for data analysis in the social sciences. We will use [RStudio](https://www.rstudio.com/) as a user friendly interface for R. R is freeware and you can download it on your personal laptop and desktop computers (along with RStudio, which is a user friendly interface for R).  Lab computers will also have R and RStudio.  Note that although the course does not require students to have experience with R, this class does not devote too much time introducing students to the program.  In other words, this is a not an introduction to R programming.  The lab guides will provide as much detail as possible to execute tasks and functions, but you will likely run into tasks that will require you to go beyond the guides.  My suggestion is to (1) look up RDS or GWR as they are excellent resources and (2) if (1) fails search online.  As such, you are expected to do as much independent learning of the software as I teach in the labs.

<div style="margin-bottom:25px;">
</div>
## **Course Requirements** 

1. Assignments (4 x 15%: 60%)

Students are required to complete four homework assignments during the quarter which are due approximately every 2 weeks.  The assignments will largely correspond to the material covered in lectures and labs.  Each assignment will ask students to apply spatial methods in R. For each assignment, you will need to submit R Markdown Rmd and html files on Canvas. Assignment guidelines can be found [here](https://crd230.github.io/hw_guidelines.html). Collaboration of ideas among seminar participants is encouraged, but the assignments must be completed independently. All assignments must be submitted via Canvas.  

Late submissions will be deducted 10% per 24 hours until 72 hours after the submission due time.  After 72 hours your submission will not be graded.  No exception unless you provide documentation of your illness or bereavement before the due date.  If you cannot upload the assignment on Canvas due to technical issues, you must email it as an attachment to me by the submission due time.

2. Course project (35%)

The final course project has the following components

a. Proposal (5%)
b. Oral Presentation (5%)
c. Final written paper (25%)

Students will conduct a research project using methods discussed in class on a topic of their choosing.  A full description of the project can be found in the file final_project_description.pdf located on Canvas. The format of the written paper will follow a standard academic empirical research article: (1) Introduction; (2) Background literature; (3) Data and Methods; (4) Results; and (5) Discussion and Conclusion.  The Results and Discussion and Conclusion sections are “preliminary” in that the expectation for the project is not to complete an article that is ready for submission by the end of the quarter.  Instead, the paper will serve as a preliminary analysis for a thesis or dissertation chapter and/or a manuscript in preparation to be submitted to a journal.

The paper will have a 20-page limit. References (APA style) must be included but will not be counted towards the page limit.  Appendices are allowed and also will not be included in the page limit. Papers must use 11 or 12 point Times New Roman font, 1 inch margins, and be single spaced.  

Prospectus: Students will submit a paper prospectus which will include the research question to be investigated, why the student is interested in investigating this question, why the student is interested in investigating this question from a spatial orientation, a description of the data to be used, and problems that the student is currently or may run into.  Students will also need to create and submit a map(s) that is relevant to their question. 

Students will present their projects to the class in the final week of the quarter.  Consider the presentation to be like a brown bag seminar.  After your seminar, you incorporate feedback, adjust your models, and rewrite. The final paper is due on Canvas by Wednesday, March 20th.

3. Participation (5%)

All students are expected to actively participate, which means not only being present, but reading all material and engaging in class discussions. If you miss a class it is your responsibility to get the lecture/lab notes from classmates. Note that I will be introducing material in lecture that extends material covered in the readings. 


<div style="margin-bottom:25px;">
</div>	
## **Course Agenda**
\

The schedule is subject to revision throughout the quarter.  Please see the full syllabus for a more detailed version of the agenda

```{r echo=  FALSE, warning = FALSE, message = FALSE}
options(knitr.kable.NA = '')
library(knitr)
library(kableExtra)
library(sf)
library(tidyverse)
dt <- read_csv("/Users/noli/Documents/UCD/teaching/CRD 230/Lab/crd230.github.io/agenda.csv")
kable(dt) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%
    column_spec(1, width = "5em") %>%
    column_spec(4, width = "13em")
```


***


Website created and maintained by [Noli Brazil](https://nbrazil.faculty.ucdavis.edu/)